### ISSUE TITLE
Add more keybindings/hotkeys (e.g. vim keybindings)

### ISSUE THREAD

**Issue by nacknime-official** [PabloLec/RecoverPy#176]
As an avid keyboard user rather than a mouse user, I've encountered some inconvenience in using this awesome tool 😊
Yes, there are "up" and "down", but there's no "Enter" key for "Open" for example.

Also as a vim user (and I think not only me), it would be very good to have vim keybindings.

**Comment by PabloLec** [comment]
Hi,

Regarding vim like keybindings I could probably implement but it would be much simpler and cleaner if Textual, the TUI library I'm using, implement it upstream.
I see there is a discussion about it https://github.com/Textualize/textual/discussions/548.
Textual is under heavy development and vim like keybindings is quite common among TUI library so I guess it will come sooner or later.

About the "broken" keyboard entries such as pressing "Enter" somewhere not doing anything, I'll look into that.
I think any button should trigger an action if Enter is pressed, at TUI library level, but I'll implement it myself if it's not the case.

Textual added a few features that could be useful for RecoverPy so I need to work on UI anyway.

**Comment by PabloLec** [comment]
By the way, feel free to tell me or just go ahead if you want to contribute for anything related to this issue or AUR 🙂
