### ISSUE TITLE
Correct path to LUKS and LVM partitions

### ISSUE THREAD

**Issue by panporter** [PabloLec/RecoverPy#264]
see https://github.com/PabloLec/RecoverPy/issues/110#issuecomment-1676489683 for how to be able to work with LUKS and LVM partitions hence current version gets the paths wrong and fails to scan LUKS and LVM partitions even when mounted (and decrypted).

**Comment by PabloLec** [comment]
Hello,

Thank you for the information. I'll include these changes in a future version when I have time to work on the project. I believe it would be even better to integrate logic to retrieve the mount point without hard-coded values, and ideally without adding new dependencies.

But again, thank you for suggesting this solution.
