### ISSUE TITLE
Recover from IMG file

### ISSUE THREAD

**Issue by DRCRecoveryData** [PabloLec/RecoverPy#275]
Hi,

I do data recovery by img create by dd command, can RecoveryPy can load IMG or BIN, DSK file to carving?

Also could you explain the overwrite data recovery method you create by code?

In my case, customer 800 JPEG deleted and ovewrite 50 files, i need your detail to make a video on my youtube channel about RecoveryPy

**Comment by PabloLec** [comment]
Hello @DRCRecoveryData , RecoverPy indeed reads the blocks with `dd` from the partitions found with `lsblk`, so you should be able to read files if your .img file is mounted.
You might try:
`sudo mount -o loop your_file.img /mnt/test`

As for the search itself, RecoverPy relies on text to find files, so searching for images can be quite hit-or-miss. However, you can use it for your text files.

By the way, I recommend using a recent version of Python, ideally 3.11. There are some stability issues with the TUI library on versions 3.8 and 3.9.

**Comment by DRCRecoveryData** [comment]
Hi,

I do sdcard recovery almost but some case fragmented by overwrite data and some case partition wrong structure we can't mout it from img file
