### ISSUE TITLE
_curses.error: init_color() returned ERR

### ISSUE THREAD

**Issue by PabloLec** [PabloLec/recoverpy#3]
> I have just tried with your new release 1.0.1,  the result is the following new error.
>
>And it seems that the problem might be due to the python 3.6 library curses 。。。?
>
>Traceback (most recent call last):
>  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
>    "__main__", mod_spec)
>  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
>    exec(code, run_globals)
>  File "/usr/lib/python3.6/site-packages/recoverpy/__main__.py", line 3, in <module>
>    recoverpy.main()
>  File "/usr/lib/python3.6/site-packages/recoverpy/__init__.py", line 42, in main
>    WINDOW_HANDLER.open_parameters_menu()
>  File "/usr/lib/python3.6/site-packages/recoverpy/window_handler.py", line 21, in open_parameters_menu
>    _PARAMETERS_MENU.start()
>  File "/usr/lib/python3.6/site-packages/py_cui-0.1.3-py3.6.egg/py_cui/__init__.py", line 317, in start
>  File "/usr/lib64/python3.6/curses/__init__.py", line 94, in wrapper
>    return func(stdscr, *args, **kwds)
>  File "/usr/lib/python3.6/site-packages/py_cui-0.1.3-py3.6.egg/py_cui/__init__.py", line 1493, in _draw
>  File "/usr/lib/python3.6/site-packages/py_cui-0.1.3-py3.6.egg/py_cui/__init__.py", line 374, in _initialize_colors
>_curses.error: init_color() returned ERR

_Originally posted by @lylklb in https://github.com/PabloLec/recoverpy/issues/2#issuecomment-841893819_

> I'm not sure if it's curses' fault or terminal's.
> 
> There seems to be similar issues with old versions of putty.
> 
> Can you please tell me what terminal are you using and its version ?
> Also, can you provide the output of `echo $TERM` ?
> 
> I'll try to reproduce this error and open a new issue.

_Originally posted by @PabloLec in https://github.com/PabloLec/recoverpy/issues/2#issuecomment-842087504_

> SecureCRT 6.2~8.7、 Xmanager/Xshell 5
> 
> ```
> # echo $TERM
> vt100
> #
> ```

_Originally posted by @lylklb in https://github.com/PabloLec/recoverpy/issues/2#issuecomment-842116422_

**Comment by PabloLec** [comment]
@lylklb I think I found the cause.

I tried to install a 4 year outdated version of SecureCRT (`8.1.4 (x64 build 1443)`)  and recoverpy was still working.

But, my `TERM` environment variable was set to `xterm`. Then setting it to `vt100` broke curses so here's the catch. It seems that similar issues were occurring with ~2014 versions of PuTTY.

Can you try `export TERM="xterm-256color"` and then launch recoverpy. It should work. (Well, at least solve this issue :wink:) 
Also, if you can try `export TERM="xterm"` and launch recoverpy for science ? It does works the same way for me but just checking with your version.

If that does the trick for you, I'll release a fix.

**Comment by lylklb** [comment]
After I set up the $TERM to xterm-256color,  it really can start successfully, but just with a lot of garbage characters...！
Notes:  I might be unable to copy & paste completely the full garbage screen output here ....

# python3  -m recoverpy

                                                              Retrieve deleted or overwritten text files

 鈺攢鈹€ Select a partition to search: 鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹€鈹

**Comment by PabloLec** [comment]
Ok, we're moving forward !

Here, that's probably just wrong character encoding caused by the VT100 terminal emulator.
I'm not entirely sure I can fix this at script level as your terminal emulator config might not provide utf8 compatibility.

Can you try:
`locale` and `python -c "import sys; print(sys.stdout.encoding)"`  

To try a first fix guess, you can try :
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```
And then launch recoverpy. You'll also have to do the previous trick beforehand.

**Comment by lylklb** [comment]
After setup the SecureCRT font encoding from default to UTF-8,  it can just only normally display without the garbage characters .

But I still cannot normally use the functions inside this tool,  even with the Arrow/Pagedown/Pageup Keys .....

```
                                                              Retrieve deleted or overwritten text files

 ╭── Select a partition to search: ───────────────────╮  ╭── Enter a text to search: ──────────────────────────────────────── │                                                          │
 │ Name: vda2  -  Type: LVM2_member                                               │  │                                                                           │
 │                                                                                │  │                                                                           │

                                                                    │─         Start search         ─│


Press - q - to exit. Arrow Keys to move between widgets. Enter to enter focus mode.

```

**Comment by lylklb** [comment]
After setup the SecureCRT font encoding from default to UTF-8,  it can just only normally display without the garbage characters .

But I still cannot normally use the functions inside this tool,  even with the Arrow/Pagedown/Pageup Keys .....

```
                                                              Retrieve deleted or overwritten text files

 ╭── Select a partition to search: ───────────────────╮  ╭── Enter a text to search: 

Press - q - to exit. Arrow Keys to move between widgets. Enter to enter focus mode.

```

**Comment by PabloLec** [comment]
I'll close this issue and open a new one. #4
