### ISSUE TITLE
Malfunction with SecureCRT

### ISSUE THREAD

**Issue by PabloLec** [PabloLec/recoverpy#4]
> After setup the SecureCRT font encoding from default to UTF-8,  it can just only normally display without the garbage characters .
>
>But I still cannot normally use the functions inside this tool,  even with the Arrow/Pagedown/Pageup Keys .....
>
>```
 >                                                             Retrieve deleted or overwritten text files
>
> ╭── Select a partition to search: ───────────────────╮  ╭── Enter a text to search: >──────────────────────────────────────── │                                                          >│
> │ Name: vda2  -  Type: LVM2_member                                               │  │                                                                           │
> │                                                                                │  │                                                                           │
>
>                                                                    │─         Start search         ─│
>
>
>Press - q - to exit. Arrow Keys to move between widgets. Enter to enter focus mode.
>
>```

_Originally posted by @lylklb in https://github.com/PabloLec/recoverpy/issues/3#issuecomment-842228637_

**Comment by PabloLec** [comment]
@lylklb

So, I'm not sure your terminal is compatible at all with curses.

I can get it running using `python 3.6.0`, SecureCRT version `Version 8.1.4 (x64 build 1443)` published in 2017 in a `W10 v1909` virtual box.

Can you confirm your SecureCRT version with `Help > About` ?

Also, you can try this [sample project](https://github.com/jwlodek/py_cui_2048) made by py_cui creator.

**Comment by lylklb** [comment]
I wonder whether there are some special setups within the SecureCRT.
So you can check the emulational teminal & keyboard mapping setups within your SecureCRT ....   then you might tell me the truth.

**Comment by PabloLec** [comment]
Well, everything is default, just installed it for testing purpose.

You should download PuTTY, leave everything to default and try a run to make sure.

If your terminal is not too outdated and not weirdly tweaked, then the only potential cause I could think of is shell. I'm running it in `zsh` right now, also working with `bash` of course.

**Comment by lylklb** [comment]
Good ！  And it really seems that your recoverpy only works best with the PuTTY ！

Now I will open another new issue for finding only one partition in my system: 
Name: vda2  -  Type: LVM2_member
