### ISSUE TITLE
No module named recoverpy

### ISSUE THREAD

**Issue by rbjnazz** [PabloLec/RecoverPy#49]
Input:
``` bash
sudo python3 -m recoverpy
```
Output:
``` bash
/usr/bin/python3: No module named recoverpy
```

**Comment by PabloLec** [comment]
Hi!

This is clearly a local problem with your setup.
You may have multiple Python interpreter or the issue might just be related to the user. Anyhow, the thing is RecoverPy was  installed outside of the path in which your interpreter searches for modules.

try:
`sudo python3 -m pip install recoverpy`
then:
`sudo python3 -m recoverpy`
Should work.
