### ISSUE TITLE
IndexError when selecting certain partitions

### ISSUE THREAD

**Issue by PabloLec** [PabloLec/recoverpy#6]
>Now it should be all right with the DISK PARTITIONs,  except for the LVM entry.
>
>```
># cat  recoverpy-2021-05-20-124528.log
>Starting 'ParametersMenu' CUI window
>User is root
>Partition list generated using 'lsblk'
>5 partitions found
>Partition added to list: vda2
>Partition added to list: vdb
>Partition added to list: system-root
>Partition added to list: system-swap
>Partition added to list: vghana-lvhana
>#
>
>```
>So if you select some LVM entry,  the recoverpy would exit with the following errors: 
>
>```
>File "/usr/lib/python3.6/site-packages/recoverpy/parameters_menu.py", line 178, in >select_partition
>   selected_partition = re.findall(r"Name\:\ ([A-Za-z0-9]+)\ ", self.partition_list_cell.get())[0]
>IndexError: list index out of range
>```

_Originally posted by @lylklb in https://github.com/PabloLec/recoverpy/issues/5#issuecomment-845602281_

**Comment by PabloLec** [comment]
@lylklb It was probably just a regex error, I guess that was happening with `system-root`, `system-swap` or `vghana-lvhana`. The regex wasn't matching hyphens, It should work now. Try v1.0.7.

**Comment by lylklb** [comment]
Ok！They do work fine now.
But it seems a shortcoming that there is no progress bar while it searching ....

**Comment by PabloLec** [comment]
Perfect :)

And as for progress bar/indicator, yes, that would be a big plus.
Sadly, `grep` does not come with anything to monitor progression. I tried looking into that.
But I'll definitely give another try, there seems to be hacky solutions using `strace`. I need to find a way to not increase time complexity while giving a progression percentage, which might be tricky.
