### ISSUE TITLE
ValueError: Subsection not found

### ISSUE THREAD

**Issue by jJit0** [PabloLec/RecoverPy#73]
Hi,

I'm getting this error each time I'm searching for a string

[Screenshot](https://i.imgur.com/7OsV4Po.png)

**Comment by PabloLec** [comment]
Hi! Thanks for the report.

That's odd, it's like your searched string cannot be found in a search result.
Well this exception should not occur, I'll release a fix.

Can you give me an example of a searched string which raises this exception ?
Also, what type of partition is searched ? Ext4, NTFS, etc.
And can you maybe think about anything particular with your system ? OS, shell, etc.

**Comment by jJit0** [comment]
I know that's weird, In the search box I've added
```
ARK
camera
```
I get this error in few seconds after the search begins!!!
It's an external Ext4 HDD
About the OS and shell, I'm using Kali Linux latest version with python3.10 as default python3 and bash shell.

I've tried using recoverpy with python3.8, same results...

**Comment by PabloLec** [comment]
Thanks, I'll look into it and release a fix tomorrow :wink:

**Comment by PabloLec** [comment]
Alright!
The problem was with the newline character, multi-line search was broken. Thanks for the heads-up.
I just released a new version with a fix, it needed more work than I thought but it should be ok now.

You can download version 1.5.1 and hopefully you won't have anymore exception!

**Comment by jJit0** [comment]
Great thanks :smile: 

I'll test it right away and give you feedback tomorrow

**Comment by jJit0** [comment]
It worked perfectly, no errors encountered :smiley:

I have few suggestions though for v1.6

- Make it a cli app by default, `pipx install recoverpy` it'll install a binary file to `/usr/local/bin/recoverpy`
- Add `--tui` or `-t` for TUI interface
- The TUI is very simplistic, I recommend `pytermgui` for fancier TUI

**Comment by PabloLec** [comment]
Thanks for the feedback :wink:

Regarding the CLI, the thing is that I think it won't be practical at all.
Recoverpy uses CLI tools under the hood (lsblk, grep and dd) and the whole thing is about simplifying their usage with a UI.
Well, I don't see how I could show the user the numerous results, let him pick the right one and navigate through neighboring blocks only with CLI args.
I guess a CLI won't do better than grep.

And about the TUI library, thanks I didn't know about this one :wink: I think I finally got bug free with my current library. But if I encounter new problems maybe it will push me to switch!

**Comment by jJit0** [comment]
You're welcome :wink:

- What I meant by a cli app, is install a binary shortcut to `/usr/local/bin/` because today the only way to launch recoverpy is by doing `python3 -m recoverpy` and this method won't work with most python package managers like pipx.
The great thing with pipx is, it will install and update python apps in a virtualenvs very easily, but it needs a specified binary in `setup.py` or `pyproject.toml` that's why I can't install recoverpy with pipx

- No problem for the cli interface, I understand what you means, instead you can maybe develop a GUI interface alongside with TUI, by specifying `recoverpy --tui` or `recoverpy --gui`
The GUI interface can be a qt5 framework, what do you think ? this can be a version bump to v2.0

- Yeah `pytermgui` is so great, that you can try with their binary to test tables, color palettes, and other objects.
