### ISSUE TITLE
How to restore overwriting text files with RecoverPy?

### ISSUE THREAD

**Issue by me-suzy** [PabloLec/RecoverPy#75]
hello. I succesfull install the extension. How can I use the extension? Is there a code for this?

How can I use it with python, to restore overwriting text files?

**Comment by PabloLec** [comment]
Hi!

You can refer to the installation and usage parts of the readme.
The most straightforward way would be:

`sudo python3 -m pip install recoverpy`
To install

`sudo python3 -m recoverpy`
To use

Make sure you're on a Linux system with root privileges. You can also take a look at the dependencies in the readme.
