### ISSUE TITLE
ImportError: cannot import name 'geteuid' from 'os' (C:\Program Files\Python39\lib\os.py

### ISSUE THREAD

**Issue by me-suzy** [PabloLec/RecoverPy#77]
hello. I successfully installed the library.

Then, I try to run on windows10 all this 3 commands with CMD or POWERSHELL:

**`py -m recoverpy`** 
**`python -m recoverpy`**
**`python3 -m recoverpy`**

also I install this command:

**`pip install https://github.com/matthewolckers/fbr2020`**

But, again, I got this error:

**`ImportError: cannot import name 'geteuid' from 'os' (C:\Program Files\Python39\lib\os.py`**

[https://snipboard.io/2lZREH.jpg](https://snipboard.io/2lZREH.jpg)

**Comment by PabloLec** [comment]
Hello,

As mentioned in the readme, Recoverpy is currently only available for Linux systems.
It could be adapted for MacOS but really hardly for Windows.
