### ISSUE TITLE
MacOS compatibility

### ISSUE THREAD

**Issue by PabloLec** [PabloLec/RecoverPy#8]
Currently, RecoverPy only works with Linux systems.
This is due to the different tools it uses under the hood but theoretically it could be adapted to work on macOS.

`grep`, `dd` and even `progress` are compatible with macOS, so no change needed here.
But `lsblk` is not, so here is the first difference.

Additions needed I can think of right now are:
- Detect if OS is Linux or macOS (done).

- Probably use `diskutil list` as a replacement for `lsblk`.
  Adding `-plist` outputs, I think, all the informations needed. And it can be parsed with native `plistlib`.
  So a function using `diskutil` needs to be added with a list of list as an output like so:
  ```
  [['NAME(e.g: disk0s2)', 'TYPE(disk/part)', 'FILESYSTEM(e.g: APFS)', MOUNTPOINT(if mounted)'], ... ]
  ```
  Although output format can be changed, modifications should also be made to linux lsblk function.

- Handle macOS specific pitfalls. By that I mean disk/partitions types and filesystems that are not present with Linux but which should be handled differently here (e.g: loopback, temp parts, non compatible with grep, etc.).

- And finally, another macOS pitfall which is permission. `sudo` only will not do the trick here. It seems like the user needs to grant "full disk access" to the Terminal though the GUI system settings beforehand. We could, maybe, find some hacky solution but otherwise, the `Operation not permitted` exception should be handled. And the sooner the better, preferably before initiating `grep` search.

I started working on it, there is not a lot to do.
But as I'm not too familiar with macOS and testing on a VM, I'm quite sure I'll miss things I should consider and it will end up being flawed.

**So, if you're a macOS user, familiar with Python, `diskutil` or essentially have some notions in macOS partition management, I would greatly welcome your help :wink:**

**Comment by ChristoferK** [comment]
> Currently, RecoverPy only works with Linux systems.

Then the repository ought not to be tagged for **`macos`**.
That was an extremely frustrating dead-end to be (*mis*)led into.

**Comment by miiraheart** [comment]
Hello any updates on this ? the repository is still tagged for `macos` and it was a dead-end on my end too. Any chance for this to be possible in the future ?
